-config replacer.full_list(0).description=Ignore Next.js dev assets
-config replacer.full_list(0).enabled=true
-config replacer.full_list(0).matchtype=REQ_HEADER
-config replacer.full_list(0).matchstr=User-Agent
-config replacer.full_list(0).regex=false
-config replacer.full_list(0).replacement=ZAP
