apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  strategy:
    canary:
      stableService: {{ .Release.Name }}-stable
      canaryService: {{ .Release.Name }}-canary
      maxSurge: {{ .Values.rollout.canary.maxSurge | quote }}
      maxUnavailable: {{ .Values.rollout.canary.maxUnavailable | quote }}
      steps:
        {{- toYaml .Values.rollout.canary.steps | nindent 8 }}
