import type { ErrorSeverity, RemediationHint } from '@/lib/errors/types';

export type ErrorCatalogEntry = {
  code: number;
  name: string;
  severity: ErrorSeverity;
  httpStatus: number;
  developerMessage: string;
  userMessageKey: string;
  remediationHints?: RemediationHint[];
  rootCauses: string[];
  resolutionSteps: string[];
};

export const ERROR_CATALOG = {
  1000: {
    code: 1000,
    name: 'CLIENT_BAD_REQUEST',
    severity: 'LOW',
    httpStatus: 400,
    developerMessage: 'Bad request',
    userMessageKey: 'errorBadRequest',
    remediationHints: [{ title: 'Check request payload and retry.' }],
    rootCauses: ['Malformed JSON', 'Missing required parameters'],
    resolutionSteps: ['Validate request payload format', 'Ensure required fields are provided'],
  },
  1001: {
    code: 1001,
    name: 'CLIENT_VALIDATION_FAILED',
    severity: 'LOW',
    httpStatus: 422,
    developerMessage: 'Validation failed',
    userMessageKey: 'errorValidationFailed',
    remediationHints: [{ title: 'Fix the highlighted fields and retry.' }],
    rootCauses: ['Invalid field values', 'Missing required fields'],
    resolutionSteps: ['Review field-level errors', 'Provide valid values for all required fields'],
  },
  1002: {
    code: 1002,
    name: 'CLIENT_RATE_LIMITED',
    severity: 'MEDIUM',
    httpStatus: 429,
    developerMessage: 'Too many requests',
    userMessageKey: 'errorRateLimited',
    remediationHints: [{ title: 'Wait a moment and retry.' }],
    rootCauses: ['Repeated requests in a short time window'],
    resolutionSteps: ['Back off and retry later', 'Avoid repeated submissions'],
  },
  1003: {
    code: 1003,
    name: 'CLIENT_NOT_FOUND',
    severity: 'LOW',
    httpStatus: 404,
    developerMessage: 'Resource not found',
    userMessageKey: 'errorNotFound',
    remediationHints: [{ title: 'Refresh the page or return to a valid screen.' }],
    rootCauses: ['Invalid resource identifier', 'Resource deleted'],
    resolutionSteps: ['Verify the identifier', 'Check that the resource exists'],
  },
  2000: {
    code: 2000,
    name: 'AUTH_UNAUTHENTICATED',
    severity: 'MEDIUM',
    httpStatus: 401,
    developerMessage: 'Authentication required',
    userMessageKey: 'errorUnauthenticated',
    remediationHints: [{ title: 'Sign in and retry.' }],
    rootCauses: ['Missing token', 'Invalid token'],
    resolutionSteps: ['Re-authenticate', 'Clear cookies and sign in again'],
  },
  2001: {
    code: 2001,
    name: 'AUTH_FORBIDDEN',
    severity: 'MEDIUM',
    httpStatus: 403,
    developerMessage: 'Not authorized',
    userMessageKey: 'errorForbidden',
    remediationHints: [{ title: 'Contact an administrator if you believe this is incorrect.' }],
    rootCauses: ['Insufficient role/permissions'],
    resolutionSteps: ['Verify user role', 'Grant permissions if appropriate'],
  },
  2002: {
    code: 2002,
    name: 'AUTH_INVALID_CREDENTIALS',
    severity: 'LOW',
    httpStatus: 401,
    developerMessage: 'Invalid credentials',
    userMessageKey: 'errorInvalidCredentials',
    remediationHints: [{ title: 'Verify your CIN and password and retry.' }],
    rootCauses: ['Wrong CIN', 'Wrong password'],
    resolutionSteps: ['Ensure CIN is correct', 'Reset password if necessary'],
  },
  2003: {
    code: 2003,
    name: 'AUTH_SESSION_EXPIRED',
    severity: 'LOW',
    httpStatus: 401,
    developerMessage: 'Session expired',
    userMessageKey: 'errorSessionExpired',
    remediationHints: [{ title: 'Sign in again.' }],
    rootCauses: ['Expired token', 'Revoked session'],
    resolutionSteps: ['Re-authenticate', 'Update token expiration policy if needed'],
  },
  3000: {
    code: 3000,
    name: 'BUSINESS_RULE_VIOLATION',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'Business rule violation',
    userMessageKey: 'errorBusinessRule',
    remediationHints: [{ title: 'Review the action and try again.' }],
    rootCauses: ['Action not allowed in current state'],
    resolutionSteps: ['Validate state transitions', 'Update UI to prevent invalid actions'],
  },
  3001: {
    code: 3001,
    name: 'BUSINESS_ALREADY_EXISTS',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'Resource already exists',
    userMessageKey: 'errorAlreadyExists',
    remediationHints: [{ title: 'Use a different identifier or sign in.' }],
    rootCauses: ['Unique constraint violation'],
    resolutionSteps: ['Check existing resources', 'Handle duplicates gracefully'],
  },
  4000: {
    code: 4000,
    name: 'EXTERNAL_SERVICE_FAILED',
    severity: 'HIGH',
    httpStatus: 502,
    developerMessage: 'External service failure',
    userMessageKey: 'errorExternalService',
    remediationHints: [{ title: 'Try again later.' }],
    rootCauses: ['Third-party API outage', 'Network errors'],
    resolutionSteps: ['Check provider status', 'Retry with backoff', 'Use fallback if available'],
  },
  4001: {
    code: 4001,
    name: 'EXTERNAL_TWILIO_FAILED',
    severity: 'HIGH',
    httpStatus: 502,
    developerMessage: 'Twilio notification failed',
    userMessageKey: 'errorNotificationFailed',
    remediationHints: [{ title: 'Try again later; the report may still be saved.' }],
    rootCauses: ['Twilio API error', 'Invalid credentials', 'Provider outage'],
    resolutionSteps: ['Verify Twilio config', 'Inspect provider error code', 'Retry later'],
  },
  4002: {
    code: 4002,
    name: 'EXTERNAL_WEATHER_FAILED',
    severity: 'MEDIUM',
    httpStatus: 502,
    developerMessage: 'Weather provider failed',
    userMessageKey: 'errorWeatherFailed',
    remediationHints: [{ title: 'Refresh later.' }],
    rootCauses: ['Weather API timeout', 'Provider outage'],
    resolutionSteps: ['Check provider status', 'Retry later'],
  },
  4003: {
    code: 4003,
    name: 'EXTERNAL_EFFIS_FAILED',
    severity: 'MEDIUM',
    httpStatus: 502,
    developerMessage: 'EFFIS Copernicus service failed',
    userMessageKey: 'errorEffisFailed',
    remediationHints: [{ title: 'EFFIS data temporarily unavailable. FIRMS data is still available.' }],
    rootCauses: ['EFFIS WFS timeout', 'Copernicus service outage'],
    resolutionSteps: ['Check EFFIS service status', 'Retry later', 'Fall back to FIRMS-only data'],
  },
  5000: {
    code: 5000,
    name: 'SYSTEM_UNEXPECTED',
    severity: 'CRITICAL',
    httpStatus: 500,
    developerMessage: 'Unexpected server error',
    userMessageKey: 'errorServer',
    remediationHints: [{ title: 'Try again later.' }],
    rootCauses: ['Unhandled exception'],
    resolutionSteps: ['Inspect logs using requestId', 'Add handling for the failure mode'],
  },
  5001: {
    code: 5001,
    name: 'SYSTEM_CONFIG_MISSING',
    severity: 'CRITICAL',
    httpStatus: 500,
    developerMessage: 'Missing server configuration',
    userMessageKey: 'errorConfigMissing',
    remediationHints: [{ title: 'Create .env.local from .env.example and restart the server.' }],
    rootCauses: ['Missing required environment variables'],
    resolutionSteps: ['Set DATABASE_URL and JWT_SECRET', 'Restart the server'],
  },
  5002: {
    code: 5002,
    name: 'SYSTEM_DATABASE_FAILED',
    severity: 'CRITICAL',
    httpStatus: 500,
    developerMessage: 'Database operation failed',
    userMessageKey: 'errorServer',
    remediationHints: [{ title: 'Try again later.' }],
    rootCauses: ['Database connectivity issue', 'Query error'],
    resolutionSteps: ['Check database connection', 'Inspect Prisma errors in logs'],
  },
  5003: {
    code: 5003,
    name: 'EXTERNAL_API_TIMEOUT',
    severity: 'HIGH',
    httpStatus: 504,
    developerMessage: 'External API request timeout',
    userMessageKey: 'errorExternalTimeout',
    remediationHints: [{ title: 'Try again in a moment.' }],
    rootCauses: ['Network latency', 'Slow external service'],
    resolutionSteps: ['Retry with exponential backoff', 'Check timeout configuration'],
  },
  5004: {
    code: 5004,
    name: 'EXTERNAL_API_AUTH_FAILED',
    severity: 'CRITICAL',
    httpStatus: 502,
    developerMessage: 'External API authentication failed - check API credentials',
    userMessageKey: 'errorExternalApiAuth',
    remediationHints: [
      { title: 'Verify API key in environment variables.' },
      { title: 'Obtain new API key from https://firms.modaps.eosdis.nasa.gov/api/area/' },
      { title: 'Check if API key is expired or revoked.' }
    ],
    rootCauses: ['Invalid API key', 'Expired API key', 'Revoked API credentials'],
    resolutionSteps: [
      'Verify FIRMS_MAP_KEY in environment variables',
      'Obtain new API key from NASA FIRMS',
      'Restart server after updating credentials'
    ],
  },
  // ============================================
  // Dispatch System Errors (6000-6099)
  // ============================================
  6000: {
    code: 6000,
    name: 'DISPATCH_ROUTING_TIMEOUT',
    severity: 'HIGH',
    httpStatus: 504,
    developerMessage: 'Routing service request timeout',
    userMessageKey: 'errorRoutingTimeout',
    remediationHints: [{ title: 'Try again in a moment.' }],
    rootCauses: ['GraphHopper timeout', 'Network latency', 'Slow routing calculation'],
    resolutionSteps: ['Retry request', 'Check GraphHopper service status', 'Verify network connectivity'],
  },
  6001: {
    code: 6001,
    name: 'DISPATCH_ROUTE_NOT_FOUND',
    severity: 'MEDIUM',
    httpStatus: 404,
    developerMessage: 'No route found between origin and destination',
    userMessageKey: 'errorRouteNotFound',
    remediationHints: [{ title: 'Verify coordinates and try a different routing profile.' }],
    rootCauses: ['Invalid coordinates', 'Unreachable destination', 'Profile constraints too strict'],
    resolutionSteps: ['Validate coordinates are within service area', 'Try different routing profile'],
  },
  6002: {
    code: 6002,
    name: 'DISPATCH_INVALID_COORDINATES',
    severity: 'LOW',
    httpStatus: 422,
    developerMessage: 'Invalid coordinates provided',
    userMessageKey: 'errorInvalidCoordinates',
    remediationHints: [{ title: 'Ensure coordinates are in [longitude, latitude] format.' }],
    rootCauses: ['Malformed coordinates', 'Out of range values'],
    resolutionSteps: ['Validate longitude is between -180 and 180', 'Validate latitude is between -90 and 90'],
  },
  6003: {
    code: 6003,
    name: 'DISPATCH_TEAM_UNAVAILABLE',
    severity: 'MEDIUM',
    httpStatus: 409,
    developerMessage: 'Team is not available for dispatch',
    userMessageKey: 'errorTeamUnavailable',
    remediationHints: [{ title: 'Select a different team with AVAILABLE status.' }],
    rootCauses: ['Team already assigned', 'Team status is EN_ROUTE, ON_SCENE, or UNAVAILABLE'],
    resolutionSteps: ['Check team status', 'Wait for team to return to AVAILABLE'],
  },
  6004: {
    code: 6004,
    name: 'DISPATCH_MAX_TEAMS_EXCEEDED',
    severity: 'LOW',
    httpStatus: 422,
    developerMessage: 'Maximum teams per incident exceeded',
    userMessageKey: 'errorMaxTeamsExceeded',
    remediationHints: [{ title: 'Maximum 5 teams can be assigned to one incident.' }],
    rootCauses: ['Too many teams selected'],
    resolutionSteps: ['Reduce team count to 5 or fewer'],
  },
  6005: {
    code: 6005,
    name: 'DISPATCH_DUPLICATE_ASSIGNMENT',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'Team already assigned to this incident',
    userMessageKey: 'errorDuplicateAssignment',
    remediationHints: [{ title: 'This team is already assigned to the incident.' }],
    rootCauses: ['Attempting to assign same team twice'],
    resolutionSteps: ['Check existing assignments', 'Select a different team'],
  },
  6006: {
    code: 6006,
    name: 'DISPATCH_ROUTING_SERVICE_UNAVAILABLE',
    severity: 'HIGH',
    httpStatus: 502,
    developerMessage: 'Routing service unavailable',
    userMessageKey: 'errorRoutingServiceUnavailable',
    remediationHints: [{ title: 'Try again later or contact support if issue persists.' }],
    rootCauses: ['GraphHopper service down', 'Network connectivity issue', 'Mapbox fallback also failed'],
    resolutionSteps: ['Check GraphHopper container status', 'Verify GRAPHHOPPER_URL in environment', 'Check Mapbox API key'],
  },
  6007: {
    code: 6007,
    name: 'DISPATCH_INVALID_ROUTE',
    severity: 'MEDIUM',
    httpStatus: 422,
    developerMessage: 'Invalid route data provided',
    userMessageKey: 'errorInvalidRoute',
    remediationHints: [{ title: 'Route data is malformed or incomplete.' }],
    rootCauses: ['Missing route coordinates', 'Invalid GeoJSON LineString'],
    resolutionSteps: ['Validate route GeoJSON structure', 'Ensure coordinates array is not empty'],
  },
  6008: {
    code: 6008,
    name: 'DISPATCH_INCIDENT_NOT_FOUND',
    severity: 'MEDIUM',
    httpStatus: 404,
    developerMessage: 'Incident not found',
    userMessageKey: 'errorIncidentNotFound',
    remediationHints: [{ title: 'Verify the incident ID and try again.' }],
    rootCauses: ['Invalid incident ID', 'Incident deleted'],
    resolutionSteps: ['Check incident exists in database', 'Refresh incident list'],
  },
  6009: {
    code: 6009,
    name: 'DISPATCH_TEAM_NOT_FOUND',
    severity: 'MEDIUM',
    httpStatus: 404,
    developerMessage: 'Team not found',
    userMessageKey: 'errorTeamNotFound',
    remediationHints: [{ title: 'Verify the team ID and try again.' }],
    rootCauses: ['Invalid team ID', 'Team deleted'],
    resolutionSteps: ['Check team exists in database', 'Refresh team list'],
  },
  // ============================================
  // Vehicle Dispatch Errors (7000-7099)
  // ============================================
  7000: {
    code: 7000,
    name: 'VEHICLE_NOT_FOUND',
    severity: 'MEDIUM',
    httpStatus: 404,
    developerMessage: 'Vehicle not found',
    userMessageKey: 'errorVehicleNotFound',
    remediationHints: [{ title: 'Verify the vehicle ID and try again.' }],
    rootCauses: ['Invalid vehicle ID', 'Vehicle deleted'],
    resolutionSteps: ['Check vehicle exists in database', 'Refresh vehicle list'],
  },
  7001: {
    code: 7001,
    name: 'VEHICLE_UNAVAILABLE',
    severity: 'MEDIUM',
    httpStatus: 409,
    developerMessage: 'Vehicle is not available for dispatch',
    userMessageKey: 'errorVehicleUnavailable',
    remediationHints: [{ title: 'Select a different vehicle with AVAILABLE status.' }],
    rootCauses: ['Vehicle already assigned', 'Vehicle status is EN_ROUTE, ON_SCENE, or OUT_OF_SERVICE'],
    resolutionSteps: ['Check vehicle status', 'Wait for vehicle to return to AVAILABLE'],
  },
  7002: {
    code: 7002,
    name: 'VEHICLE_INVALID_TELEMETRY',
    severity: 'LOW',
    httpStatus: 422,
    developerMessage: 'Invalid telemetry data',
    userMessageKey: 'errorVehicleInvalidTelemetry',
    remediationHints: [{ title: 'Ensure position is a valid GeoJSON Point.' }],
    rootCauses: ['Malformed position data', 'Invalid coordinates'],
    resolutionSteps: ['Validate position format', 'Ensure coordinates are [longitude, latitude]'],
  },
  7003: {
    code: 7003,
    name: 'VEHICLE_DUPLICATE_CALLSIGN',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'Vehicle call sign already exists',
    userMessageKey: 'errorVehicleDuplicateCallSign',
    remediationHints: [{ title: 'Use a unique call sign for this vehicle.' }],
    rootCauses: ['Duplicate call sign'],
    resolutionSteps: ['Check existing vehicles', 'Choose a different call sign'],
  },
  7004: {
    code: 7004,
    name: 'VEHICLE_DUPLICATE_ASSIGNMENT',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'Vehicle already assigned to this incident',
    userMessageKey: 'errorVehicleDuplicateAssignment',
    remediationHints: [{ title: 'This vehicle is already assigned to the incident.' }],
    rootCauses: ['Attempting to assign same vehicle twice'],
    resolutionSteps: ['Check existing assignments', 'Select a different vehicle'],
  },
  // ============================================
  // Fire Event Record Errors (8000-8099)
  // ============================================
  8000: {
    code: 8000,
    name: 'FIRE_RECORD_NOT_FOUND',
    severity: 'LOW',
    httpStatus: 404,
    developerMessage: 'Fire event record not found',
    userMessageKey: 'errorFireRecordNotFound',
    remediationHints: [{ title: 'Verify the record ID and try again.' }],
    rootCauses: ['Invalid record ID', 'Record deleted'],
    resolutionSteps: ['Check record exists in database', 'Refresh record list'],
  },
  8001: {
    code: 8001,
    name: 'FIRE_RECORD_ALREADY_EXISTS',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'Fire event record already exists for this incident',
    userMessageKey: 'errorFireRecordAlreadyExists',
    remediationHints: [{ title: 'A record already exists for this incident.' }],
    rootCauses: ['Duplicate fire record for same incident'],
    resolutionSteps: ['View the existing record instead', 'Use the existing record ID'],
  },
  8002: {
    code: 8002,
    name: 'FIRE_RECORD_SECTION_LOCKED',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'Cannot modify a locked section',
    userMessageKey: 'errorFireRecordSectionLocked',
    remediationHints: [{ title: 'This section has been locked and cannot be modified.' }],
    rootCauses: ['Attempting to edit a finalized section'],
    resolutionSteps: ['Contact an administrator to unlock the section if needed'],
  },
  8003: {
    code: 8003,
    name: 'FIRE_RECORD_INVALID_PERIMETER',
    severity: 'LOW',
    httpStatus: 422,
    developerMessage: 'Invalid burn perimeter polygon',
    userMessageKey: 'errorFireRecordInvalidPerimeter',
    remediationHints: [{ title: 'Provide a valid GeoJSON Polygon with at least 4 coordinates.' }],
    rootCauses: ['Malformed GeoJSON', 'Invalid polygon coordinates'],
    resolutionSteps: ['Validate polygon structure', 'Ensure ring is closed'],
  },
  8004: {
    code: 8004,
    name: 'FIRE_RECORD_NOT_ALL_LOCKED',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'All sections must be locked before approval',
    userMessageKey: 'errorFireRecordNotAllLocked',
    remediationHints: [{ title: 'Lock all sections before requesting approval.' }],
    rootCauses: ['One or more sections are still unlocked'],
    resolutionSteps: ['Lock all remaining sections', 'Review unlocked sections list'],
  },
  8005: {
    code: 8005,
    name: 'FIRE_RECORD_ALREADY_LOCKED',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'Record is already locked and cannot be modified',
    userMessageKey: 'errorFireRecordAlreadyLocked',
    remediationHints: [{ title: 'Locked records are immutable.' }],
    rootCauses: ['Attempting to edit a locked record'],
    resolutionSteps: ['View the record in read-only mode'],
  },
  8006: {
    code: 8006,
    name: 'FIRE_RECORD_INCIDENT_NOT_FOUND',
    severity: 'LOW',
    httpStatus: 404,
    developerMessage: 'Incident not found for fire record creation',
    userMessageKey: 'errorFireRecordIncidentNotFound',
    remediationHints: [{ title: 'Verify the incident ID exists.' }],
    rootCauses: ['Invalid incident ID', 'Incident deleted'],
    resolutionSteps: ['Check incident exists', 'Refresh incident list'],
  },
  8007: {
    code: 8007,
    name: 'FIRE_RECORD_INVALID_TRANSITION',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'Invalid record status transition',
    userMessageKey: 'errorFireRecordInvalidTransition',
    remediationHints: [{ title: 'This status transition is not allowed.' }],
    rootCauses: ['Invalid state machine transition'],
    resolutionSteps: ['Follow the DRAFT → VERIFIED → LOCKED workflow'],
  },
  8008: {
    code: 8008,
    name: 'FIRE_RECORD_EXPORT_FAILED',
    severity: 'MEDIUM',
    httpStatus: 500,
    developerMessage: 'Failed to export fire records',
    userMessageKey: 'errorFireRecordExportFailed',
    remediationHints: [{ title: 'Try again later.' }],
    rootCauses: ['Database query failure', 'Export formatting error'],
    resolutionSteps: ['Retry the export', 'Check server logs'],
  },
  8009: {
    code: 8009,
    name: 'FIRE_RECORD_IMPORT_FAILED',
    severity: 'MEDIUM',
    httpStatus: 500,
    developerMessage: 'Failed to import FIRMS detections as fire records',
    userMessageKey: 'errorFireRecordImportFailed',
    remediationHints: [{ title: 'Check FIRMS detection data and try again.' }],
    rootCauses: ['Invalid detection data', 'Database write failure'],
    resolutionSteps: ['Validate detection payload', 'Check server logs'],
  },
  8010: {
    code: 8010,
    name: 'FIRE_RECORD_COMPARE_FAILED',
    severity: 'LOW',
    httpStatus: 422,
    developerMessage: 'Failed to compare fire records',
    userMessageKey: 'errorFireRecordCompareFailed',
    remediationHints: [{ title: 'Select 2-5 records to compare.' }],
    rootCauses: ['Invalid record IDs', 'Too many or too few records selected'],
    resolutionSteps: ['Provide 2-5 valid record IDs'],
  },
  8011: {
    code: 8011,
    name: 'FIRE_RECORD_VERIFY_FAILED',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'Cannot verify this record',
    userMessageKey: 'errorFireRecordVerifyFailed',
    remediationHints: [{ title: 'Only DRAFT records can be verified.' }],
    rootCauses: ['Record is not in DRAFT status'],
    resolutionSteps: ['Ensure record is in DRAFT status before verifying'],
  },
  8012: {
    code: 8012,
    name: 'FIRE_RECORD_PDF_FAILED',
    severity: 'MEDIUM',
    httpStatus: 500,
    developerMessage: 'Failed to generate fire record PDF',
    userMessageKey: 'errorFireRecordPdfFailed',
    remediationHints: [{ title: 'Try again later.' }],
    rootCauses: ['PDF generation error', 'Missing record data'],
    resolutionSteps: ['Retry the export', 'Check server logs'],
  },
  // ============================================
  // Coordination System Errors (9000-9099)
  // ============================================
  9000: {
    code: 9000,
    name: 'COORDINATION_AGENCY_NOT_FOUND',
    severity: 'LOW',
    httpStatus: 404,
    developerMessage: 'Agency status not found',
    userMessageKey: 'errorCoordinationAgencyNotFound',
    remediationHints: [{ title: 'Verify the agency identifier and try again.' }],
    rootCauses: ['Invalid agency enum value', 'Agency not seeded'],
    resolutionSteps: ['Check agency exists in AgencyStatus table', 'Run seed or auto-init'],
  },
  9001: {
    code: 9001,
    name: 'COORDINATION_INVALID_POI_LEVEL',
    severity: 'LOW',
    httpStatus: 422,
    developerMessage: 'Invalid POI activation level',
    userMessageKey: 'errorCoordinationInvalidPOI',
    remediationHints: [{ title: 'Provide a valid POI level (POI_1, POI_2, or POI_3).' }],
    rootCauses: ['Invalid POI level value'],
    resolutionSteps: ['Use POI_1, POI_2, or POI_3'],
  },
  9002: {
    code: 9002,
    name: 'COORDINATION_LOG_FAILED',
    severity: 'MEDIUM',
    httpStatus: 500,
    developerMessage: 'Failed to create communication log entry',
    userMessageKey: 'errorCoordinationLogFailed',
    remediationHints: [{ title: 'Try again later.' }],
    rootCauses: ['Database write failure'],
    resolutionSteps: ['Check database connectivity', 'Inspect server logs'],
  },
  9003: {
    code: 9003,
    name: 'COORDINATION_PMA_INVALID_STEP',
    severity: 'LOW',
    httpStatus: 422,
    developerMessage: 'Invalid PMA workflow step transition',
    userMessageKey: 'errorCoordinationPMAInvalidStep',
    remediationHints: [{ title: 'Steps must be advanced sequentially.' }],
    rootCauses: ['Attempting to skip PMA steps', 'Invalid step transition'],
    resolutionSteps: ['Follow the sequential PMA step order'],
  },
  9004: {
    code: 9004,
    name: 'COORDINATION_MUTUAL_AID_FAILED',
    severity: 'MEDIUM',
    httpStatus: 500,
    developerMessage: 'Mutual aid request operation failed',
    userMessageKey: 'errorCoordinationMutualAidFailed',
    remediationHints: [{ title: 'Try again later.' }],
    rootCauses: ['Database write failure', 'Invalid status transition'],
    resolutionSteps: ['Check database connectivity', 'Verify status transition is valid'],
  },
  // ============================================
  // Operations / Campaign Errors (10000-10099)
  // ============================================
  10000: {
    code: 10000,
    name: 'CAMPAIGN_NOT_FOUND',
    severity: 'LOW',
    httpStatus: 404,
    developerMessage: 'Campaign not found',
    userMessageKey: 'errorOperationsCampaignNotFound',
    remediationHints: [{ title: 'Verify the campaign ID and try again.' }],
    rootCauses: ['Invalid campaign ID', 'Campaign deleted'],
    resolutionSteps: ['Check campaign exists in database', 'Refresh campaign list'],
  },
  10001: {
    code: 10001,
    name: 'CAMPAIGN_ALREADY_EXISTS',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'A campaign already exists for this year',
    userMessageKey: 'errorOperationsCampaignExists',
    remediationHints: [{ title: 'A campaign for this year already exists.' }],
    rootCauses: ['Duplicate year constraint violation'],
    resolutionSteps: ['Use a different year or edit the existing campaign'],
  },
  10002: {
    code: 10002,
    name: 'INVALID_PHASE_TRANSITION',
    severity: 'LOW',
    httpStatus: 409,
    developerMessage: 'Cannot advance phase — already at the last phase',
    userMessageKey: 'errorOperationsInvalidPhase',
    remediationHints: [{ title: 'The campaign is already at the final phase.' }],
    rootCauses: ['Attempting to advance past POST_CAMPAGNE'],
    resolutionSteps: ['Close the campaign instead of advancing'],
  },
  10003: {
    code: 10003,
    name: 'CHECKLIST_NOT_FOUND',
    severity: 'LOW',
    httpStatus: 404,
    developerMessage: 'Checklist item not found',
    userMessageKey: 'errorOperationsChecklistNotFound',
    remediationHints: [{ title: 'Verify the checklist item ID.' }],
    rootCauses: ['Invalid checklist ID', 'Item deleted'],
    resolutionSteps: ['Refresh the checklist'],
  },
  10004: {
    code: 10004,
    name: 'CHECKLIST_UPDATE_FAILED',
    severity: 'MEDIUM',
    httpStatus: 500,
    developerMessage: 'Failed to update checklist item',
    userMessageKey: 'errorOperationsChecklistUpdateFailed',
    remediationHints: [{ title: 'Try again later.' }],
    rootCauses: ['Database write failure'],
    resolutionSteps: ['Check database connectivity', 'Inspect server logs'],
  },
  // ============================================
  // Equipment / Retardant / Infrastructure (11000-11099)
  // ============================================
  11000: {
    code: 11000,
    name: 'EQUIPMENT_NOT_FOUND',
    severity: 'LOW',
    httpStatus: 404,
    developerMessage: 'Equipment not found',
    userMessageKey: 'errorEquipmentNotFound',
    remediationHints: [{ title: 'Verify the equipment ID and try again.' }],
    rootCauses: ['Invalid equipment ID', 'Equipment deleted'],
    resolutionSteps: ['Check equipment exists in database', 'Refresh equipment list'],
  },
  11001: {
    code: 11001,
    name: 'RETARDANT_NOT_FOUND',
    severity: 'LOW',
    httpStatus: 404,
    developerMessage: 'Retardant product not found',
    userMessageKey: 'errorRetardantNotFound',
    remediationHints: [{ title: 'Verify the retardant product ID and try again.' }],
    rootCauses: ['Invalid retardant ID', 'Product deleted'],
    resolutionSteps: ['Check product exists in database', 'Refresh retardant list'],
  },
  11002: {
    code: 11002,
    name: 'INFRASTRUCTURE_NOT_FOUND',
    severity: 'LOW',
    httpStatus: 404,
    developerMessage: 'Infrastructure not found',
    userMessageKey: 'errorInfrastructureNotFound',
    remediationHints: [{ title: 'Verify the infrastructure ID and try again.' }],
    rootCauses: ['Invalid infrastructure ID', 'Infrastructure deleted'],
    resolutionSteps: ['Check infrastructure exists in database', 'Refresh infrastructure list'],
  },
  11003: {
    code: 11003,
    name: 'EQUIPMENT_VALIDATION_FAILED',
    severity: 'LOW',
    httpStatus: 400,
    developerMessage: 'Equipment validation failed',
    userMessageKey: 'errorEquipmentValidationFailed',
    remediationHints: [{ title: 'Check required fields and try again.' }],
    rootCauses: ['Missing required fields', 'Invalid field values'],
    resolutionSteps: ['Provide all required fields', 'Check field value constraints'],
  },
} as const satisfies Record<number, ErrorCatalogEntry>;

export type ErrorCatalogCode = keyof typeof ERROR_CATALOG;

export function getCatalogEntry(code: number): ErrorCatalogEntry {
  return (ERROR_CATALOG as Record<number, ErrorCatalogEntry>)[code] ?? ERROR_CATALOG[5000];
}

